### ISSUE TITLE
Update checker doesn't works with umod.org

### ISSUE THREAD

**Issue by Melodeiro** [umods/UpdateChecker#2]
Hello!
Well, it seems to work only with plugins, where resourceid has been set. But there is a lot of plugins on umod.org, where its isn't. So it gives a warning: 

> (22:50:59) [Warning] [Update Checker] Following plugins are missing their resourceId, and therefor cannot be checked for updates: BGrade, Bounty, DangerousTreasures, Logger, RaidTracker, SaveAnnouncer, Spectate, StartupCommands, UpdateChecker, Vanish, WaterLimits and Whisper

Seems like, it doesn't work "automatically" as it's readme mentions. Im using 2.2.1 version.
Also could you, please, add a blacklist in config, where i can put plugins, which i don't want to check updates for (because they are not from oxide/umod, also i removed them from quote above), and don't want to see a warnings.
Thank you!

Best regards,
Daniel

**Comment by LaserHydra** [comment]
That is known, and was not implemented yet. Though, now as the amount of umod plugins without resourceId is growing, I'll work on that soon.
I'll probably include a blacklist in the next update as well.

**Comment by LaserHydra** [comment]
uMod plugins are now fully supported in v2.3.0.
